### ISSUE TITLE
Permit styles to be specified by rich Theme instance

### ISSUE THREAD

**Issue by RhetTbull** [daylinmorgan/click-rich-help#3]
It would be helpful if styles for `StyledGroup` and `StyledCommand` could be specified by a [rich.theme.Theme](https://rich.readthedocs.io/en/stable/style.html#style-themes) instance. 

Consider for example, instead of this:

```python
@click.group(
    cls=StyledGroup,
    headers_style="yellow bold",
    options_style="cyan italic",
    metavar_style="red bold",
)
```

if one could do this:

```python
@click.group(
    cls=StyledGroup,
    theme=Theme(
        {"headers": "yellow bold", "options": "cyan italic", "metavar": "red bold"}
    ),
)
```

Themes could thus be re-used or loaded at start-up (e.g. by passing a theme instance).  This would also make it possible to add styles to the help text, for example:

```python
@click.option(
    "--my-option",
    nargs=1,
    metavar="FOO",
    help="Do something with [metavar]FOO[/]",
)
```

If you're interested in this as a feature, I'm willing to work on a PR.  I'm using rich themes in my CLIs so I can accommodate different user preferences, dark mode, etc. without hard coding styles and I think this would be useful.  See for example [rich-theme-manager](https://github.com/RhetTbull/rich_theme_manager).

**Comment by RhetTbull** [comment]
As I've started to look at the code to see what it will take to implement this, I think it may be messy to allow both the named args (e.g. `headers_style`) and a theme.  What if both were passed?  Which would take precedence? What if a theme were passed that didn't specify all the colors? 

If I were implementing this from scratch, I'd use only a rich `Theme` instance.  

Advantages:

- The same theme can define multiple other styles used elsewhere in the program
- The theme could be changed at load time (e.g. detect dark mode or allow user to set their own default theme (as is done by [rich_theme_manager](https://github.com/RhetTbull/rich_theme_manager)
- New styles can be easily added in the future without changing the interface
- Programmer can directly access styles in the help text

Disadvantages:

- Less help for the programmer from the editor (e.g. no named args or no notification if style name misspelled or missing in the `Theme` instance)
- Less declarative about intent

Thoughts on changing the interface to support just themes or both themes and named arg styles?

I could fork and create a new package that only supports themes but the field is already crowded in the "rich click help" category:

- [click-rich-help](https://github.com/daylinmorgan/click-rich-help): this package; does not appear to be widely used
- [click-help-colors](https://github.com/click-contrib/click-help-colors): package this was based on; 279k downloads/month, in use by at least 1k other Github projects
- [rich-click](https://github.com/ewels/rich-click): more stars but less widely used; opinionated; output differs from standard click output; must be configured through a plethora of global variables; I find the dual markdown/rich support (configured via global variable) confusing; has some [issues](https://github.com/ewels/rich-click/issues/19) that make it incompatible with custom `get_help` functions or paging; 

Do we need another "rich click help" type package?  On the other hand, I feel strongly programmers ought to take advantage of rich themes so styles aren't hard coded all over the place.  For example, supporting different terminal colors or supporting users who are color blind. I think being able to configure click help via a rich theme is an elegant alternative to some of these other solutions.

**Comment by daylinmorgan** [comment]
This isn't a bad idea and I agree giving users more modular control over styling to the extent apps want to support it might be nice. 

I think maintaining the named args won't be that complicated. As long the precedence order is well documented, it shouldn't make much difference which the user prefers. 

They can be given lower precedence than a `rich.theme.Theme`  configuration. 

Under the hood it might be simplest to convert the named args to a starting `Theme` and attach it to the console instance. Then  if the user provides a theme at instantiation of the class/`click` command it can just overwrite any keyword arguments given to the class.

**Comment by RhetTbull** [comment]
> Under the hood it might be simplest to convert the named args to a starting Theme and attach it to the console instance. Then if the user provides a theme at instantiation of the class/click command it can just overwrite any keyword arguments given to the class.

I think that's a good approach.  I'll take a stab at a PR to implement this.

**Comment by daylinmorgan** [comment]
I had a free minute and pretty much got this working. 

I plan to also allow the below syntax so users don't have to import `Theme` in simple cases. 

```python
@click.group(
    cls=StyledGroup,
    styles={"headers": "yellow bold", "options": "cyan italic", "metavar": "red bold"},
)
```

**Comment by RhetTbull** [comment]
This works great--thanks!

**Comment by daylinmorgan** [comment]
> If I were implementing this from scratch, I'd use only a rich Theme instance.

@RhetTbull  you were right.
Dealing with all the redundant named arg calls across the code I now agree that supporting named args isn't worth it. 

I think specifying styles in a dictionary/`Theme` works better.
